### DISCUSSION TITLE
Script installation script split vertically instead of horizontally.

### DISCUSSION THREAD

**Discussion by woj-tek** [violentmonkey/violentmonkey#2312] [General]
Recently (last 2-5 weeks?) for some reason installation script page is now split vertically (mostly 50%, with huge, empty sidebar with script info on the left) instead of horizontally (tiny header on top with script info):

![Captura de pantalla 2025-05-02 a las 10 27 59](https://github.com/user-attachments/assets/b7a23e2e-1cdc-43ae-979c-1a352598fb99)

how can I get back to the horizontal split?

**Comment by tophf** [comment]
It is automatic and depends on the width of the browser window. You can add custom CSS in the options to disable it:

```css
.page-confirm {
  flex-direction: column;
  >:first-child {
      min-width: 0;
      max-width: none;
      min-height: 5em;
      max-height: 80vh;
      width: auto !important;
      resize: vertical;
      overflow-y: auto;
  }
  .info .descr {
    max-height: 4rem;
  }
  .lists {
    overflow: hidden;
    max-height: none;
    dd {
      max-height: 10vh;
    }
  }
  .edit-externals {
    border-top: var(--border);
    border-left: none;
  }
}
```
