### ISSUE TITLE
Is it just me, or do userscripts load slower after the update?

### ISSUE THREAD

**Issue by idgas01** [violentmonkey/violentmonkey#1148]
I was using 2.12.4 and I updated to 2.12.9 around three to five days ago.  I immediately noticed a difference on Yahoo! Mail.  I created a user script for Yahoo! Mail to change the layout and appearance some.  And since the update, the userscript doesn't load fast enough so I always see the default layout.  I have to refresh the page to see the desired changes.  It doesn't always do that.  But a lot of the time it does.  Enough to make me think that 2.12.9 loads userscripts slower than 2.12.4 does.  I'm not expecting or asking you to improve this.  Just please be aware and maybe you can figure a way to make it faster.  Thank you.  I guess if it annoys me enough, I can always revert back to 2.12.4.

**Comment by tophf** [comment]
Nothing we can do here without seeing and testing the script.

**Comment by idgas01** [comment]
@tophf 

I'm only going to do this once.  I didn't want to share my userscript and I don't like showing people my emails and other personal information.  If you don't figure out the problem, I will just continue using 2.12.4 until it is broken.  And hopefully I won't be forced to switch to a different userscript add-on, because I really like Violentmonkey a lot.

I created two gifs.  One to show what my Yahoo Mail userscript does when I use 2.12.4.  And one to show what my Yahoo Mail userscript does when I use 2.12.8.  The reason I made the two gifs is because my Yahoo Mail userscript is specifically made for my personal computer and my personal settings.  If you were to try and use the Yahoo Mail userscript, you would see very different results.  That's because I am using a 1600x900 computer resolution and my Firefox Portable browser is always 1100x870.  Using any other window size would destroy the userscript.  Again, this userscript was never meant to be publicized.  It's just for my personal use.

Btw, I had reverted to 2.12.4 a long time ago, like as soon as 2.12.8 was available and I found that it would not load my userscript until I had reloaded the page (I want it to load without having to refresh the page).  I'm just now trying 2.12.8 again because I wanted to be using the most up-to-date version, but I'm still having this difficulty so I had to revert back to 2.12.4 again.

So here are the two gifs...

This shows how I want my Yahoo Mail to look.  This is what my userscript does in version 2.12.4:
https://imgur.com/eNKb1lA

This shows how the userscript does not load in 2.12.8 (until I refresh the page):
https://imgur.com/njdKMp9

And this is my actual userscript:
https://pastebin.com/vtLvRLrD

**Comment by tophf** [comment]
2.12.8 is an old version, it had a few bugs that we've fixed in the [latest beta release](https://github.com/violentmonkey/violentmonkey/releases) so try it please.

Also, waitForKeyElements is indeed not the best tool as it retries every 300ms thus potentially creating an ugly pause. A much faster solution would be to use MutationObserver. Note that those nodes that you modify directly (without `parent`) don't need waitForKeyElements/MutationObserver because you can do it via GM_addStyle:

```css
[data-test-id=mail-left-rail] {
  min-width: 275px !important;
}
[data-test-id=mail-app-component] {
  min-width: 93px !important;
}
[data-test-id=folder-list] > ul > li.H_6MWH,
[data-test-id=toggle-folder-tree], /* comment */
[data-test-id=right-rail-hidead-btn],
[data-test-id=folder-list] > div:nth-child(2) {
  display: none !important;
}
[data-test-id=folder-item-container] > a > span > span {
  min-width: 22px !important;
}
```
