### ISSUE TITLE
[feature request] List of scripts

### ISSUE THREAD

**Issue by wvxwxvw** [violentmonkey/violentmonkey#1221]
Please return the sequential display of the scripts in the script list - an ordinal list. Who even got the idea that tiles are good? We have to get rid of this "love of lamers" in Explorer, and now here too. Since you like tiles so much, make them as an option. It is inconvenient to search for the required script among several dozen.

**Comment by tophf** [comment]
It depends on the width of the screen. On a typical 1920x1080 screen the single column mode wastes 90% of space, which is why the multi-column mode was introduced. It may be unusual for some people, of course, but there's nothing inherently wrong with multi-column display because it's being the default in many modern apps and sites.

You can restore a single column using this custom CSS:

```css
.scripts {
  display: block !important;
}
.scripts .script {
  width: auto !important;
}
```
