### ISSUE TITLE
可以增加一个序号或者总数吗？

### ISSUE THREAD

**Issue by baby1128** [violentmonkey/violentmonkey#1281]
因为脚本太多，也不知道同步的脚本数量对不对，所以希望在脚本前面增加一个序号，或者显示一个脚本总数。谢谢！

**Comment by violenttamper** [comment]
我也希望，能添加

**Comment by tophf** [comment]
Use `Custom CSS` in Violetmonkey's advanced settings:

```css
.scripts {
  counter-reset: num;
}
.script-name::before {
  counter-increment: num;
  content: counter(num) ": ";
}
```
