### ISSUE TITLE
CodeMirror dark mode, highlighted text has incredibly low visibility

### ISSUE THREAD

**Issue by szc126** [violentmonkey/violentmonkey#1361]
### How to reproduce it?
1. Ctrl-F for text

### What is the expected result?

I can tell what is highlighted.

### What is the actual result?

I can't tell what is highlighted, and frankly, I don't even want code highlighting.

![it's line 288 btw](https://user-images.githubusercontent.com/29127915/132115604-c69306e7-7ba7-4cc0-98c7-e2ecc137687c.png)

### Environment
- Browser: Firefox
- Browser version: 91.0.2
- Violentmonkey version: v2.13.0
- OS: Arch Linux

**Comment by tophf** [comment]
We're using the same selection color as Chrome's devtools or many other dark themes. Your screenshot doesn't show the selected part so it doesn't illustrate the problem, but I agree the color is hard to notice so we should make it slightly brighter.

Meanwhile, you can disable syntax highlight yourself by adding `,"theme": ""` to the editor config in Violentmonkey settings and you can configure the color via `Custom CSS` in Violentmonkey settings:
```css
.CodeMirror .CodeMirror-selected,
.CodeMirror .CodeMirror-line ::selection,
.CodeMirror .CodeMirror-line ::-moz-selection {
  background: rgba(207, 194, 155, .99);
}
```
