### ISSUE TITLE
[Feature] Recycle bin relocation

### ISSUE THREAD

**Issue by jojoPL1987** [violentmonkey/violentmonkey#1709]
Violentmonkey BETA 2.13.5.1 got recycle bin in a new place:
https://i.imgur.com/1yrnu33.png

For me, the recycle bin in the new place is a bit hidden. Maybe move it? My proposition:
https://i.imgur.com/sEFUGuH.png

**Comment by tophf** [comment]
I agree. This is especially true when the display device is very tall. Maybe also rename it to "Deleted scripts" to match the sibling label? And maybe make it gray when it's empty?

**Comment by jojoPL1987** [comment]
Or add a counter of the number of scripts in the trash next to the name? E.g.:
`Recycle Bin (0)`
`Recycle Bin (1)`
`Recycle Bin (5)`
`Recycle Bin (10)`

**Comment by tophf** [comment]
It already shows the counter in the same position as the installed scripts, so it's fine.

**Comment by tophf** [comment]
Meanwhile here's a workaround via Custom CSS in settings:

```css
.aside-menu-item:nth-last-child(2) {
  flex: 0;
  order: 1;
}
.aside-menu-item:nth-last-child(3) {
  order: 1;
}
```

**Comment by jojoPL1987** [comment]
It works. But maybe put "Recycle Bin" a bit closer to "Installed scripts" and a bit further from "Settings"?

**Comment by tophf** [comment]
You can adjust it via margin-top and margin-bottom like this:
```css
.aside-menu-item:last-child {
  margin-top: -1em;
}
```
