### ISSUE TITLE
[Feature] popup UI: make it bigger - some userscripts have long names

### ISSUE THREAD

**Issue by vitaly-zdanevich** [violentmonkey/violentmonkey#2187]
My problem:
![2024-sep-17--01-45-22_maim](https://github.com/user-attachments/assets/9ab400bb-2847-4b99-b8d6-1be5c82fb01a)

As you see - I cannot read the script names :(

**Comment by tophf** [comment]
Add the following code in VM advanced settings -> Custom CSS:

```css
body:has(.page-popup) {
  width: 800px;
}
```
