### ISSUE TITLE
[BUG] The script list's display setting needs to be increased in width to accommodate the options.

### ISSUE THREAD

**Issue by Gloryandel** [violentmonkey/violentmonkey#2225]
### Sequence of actions: 

none

### Problem: 

![image_38](https://github.com/user-attachments/assets/aa47b183-1a1d-4424-855f-8eb3a54956a1)

#### Environment:
- OS: Windows
- Browser: Chrome 123 
- Violentmonkey Version: 2.28.0

**Comment by tophf** [comment]
The workaround until a new release is published is to add this in `Custom CSS` option:

```css
.vl-dropdown-menu .setting-check {
  width: max-content;
}
```
