### ISSUE TITLE
[Feature] Add option to sort in descending order

### ISSUE THREAD

**Issue by scientificworld** [violentmonkey/violentmonkey#2321]
**Motivation**

I'd like to sort by descending execution order, however I don't find a option like that.

**Proposed Solution**

Add new options in sort order like `execution (descending)`, or add a new checkbox with a label `reverse sorting`? I'm not sure which solution is better.

**Comment by cyfung1031** [comment]
such enhancement would be very low priority and this feature is only beneficial to you.. i mean almost no users sort in this way.

So I would suggest you the add the custom CSS as a temporary solution.

```css
body:has(select[value="exec"]) {

  div.scripts[class="scripts"] {
    flex-direction: row-reverse;
    flex-wrap: wrap-reverse;
  }

}
```

In the Settings page, right side(Advanced), scroll to the bottom you will see the 
```
Custom Style
Custom CSS for options page and script installation page. If you are not sure what this is for, please do not edit it.
```

Paste the above css in the textarea and save. You will see the magic immediately.
