### ISSUE TITLE
Meta data customization do not work

### ISSUE THREAD

**Issue by tiansh** [violentmonkey/violentmonkey#49]
It seems there is something wrong with `z-index` on the panel. Currently:

```css
.button-panel { z-index: 2; }
.CodeMirror-gutter-wrapper { z-index: 4; }
```
![blh-fs8](https://cloud.githubusercontent.com/assets/6500326/14745809/51a9d350-08f0-11e6-9f2d-1f276df23b63.png)
