### ISSUE TITLE
Selection style errors in CodeMirror when its inputStyle is set to contenteditable

### ISSUE THREAD

**Issue by Crystal-RainSlide** [violentmonkey/violentmonkey#825]
### What is the problem?
RT

![Example](https://user-images.githubusercontent.com/16851802/72876781-53189300-3d32-11ea-94cf-cd2c79302909.png)

### How to reproduce it?
1. Open the editor
2. Make a nested `<span>` stucture with a higher depth than 2, like a Tab in a multi-line comment
3. Select it.

### What is the expected result?

All the selected text should got a background color in `rgba(73,72,62,.99)`

### What is the actual result?

Some of the the selected text has a background color in `#fff` in Firefox;

Under dark mode, All the selected text got a background color in `#d7d4f0` in Chrome.

### Environment
- Browser: Firefox
- Browser version: 72
- Violentmonkey version: v2.12.4
- OS: Not related

### Fix
``` CSS
.CodeMirror-line::-moz-selection,
.CodeMirror-line span::-moz-selection { background:#d7d4f0; }
.CodeMirror-line::selection,
.CodeMirror-line span::selection { background:#d7d4f0; }

@media (prefers-color-scheme:dark) {
	.cm-s-eclipse .CodeMirror-line::-moz-selection,
	.cm-s-eclipse .CodeMirror-line span::-moz-selection { background:rgba(73,72,62,.99); }
	.cm-s-eclipse .CodeMirror-line::selection,
	.cm-s-eclipse .CodeMirror-line span::selection { background:rgba(73,72,62,.99); }
}
```
### Info

**Update**: Also check [#issuecomment-577233710](#issuecomment-577233710)

疑似是 CodeMirror 的样式问题，但这在手动配置、手动设置主题的 CodeMirror 编辑器上无法复现。不确定是否和 `@media (prefers-color-scheme:dark)` 有关。

目前，common.css 里与 `::selection` 相关的样式是这些：

``` CSS
.CodeMirror-gutter-wrapper ::selection {
	background-color: initial;
}
.CodeMirror-gutter-wrapper ::-moz-selection {
	background-color: initial;
}

.CodeMirror-line::selection,
.CodeMirror-line > span::selection,
.CodeMirror-line > span > span::selection {
	background: #d7d4f0;
}
.CodeMirror-line::-moz-selection,
.CodeMirror-line > span::-moz-selection,
.CodeMirror-line > span > span::-moz-selection {
	background: #d7d4f0;
}

@media (prefers-color-scheme:dark) {
	.cm-s-eclipse .CodeMirror-line::-moz-selection,
	.cm-s-eclipse .CodeMirror-line>span::-moz-selection,
	.cm-s-eclipse .CodeMirror.cm-s-eclipse .CodeMirror-line>span>span::-moz-selection {
		background: rgba(73,72,62,.99);
	}
	.cm-s-eclipse .CodeMirror-line::-moz-selection,
	.cm-s-eclipse .CodeMirror-line::selection,
	.cm-s-eclipse .CodeMirror-line>span::-moz-selection,
	.cm-s-eclipse .CodeMirror-line>span::selection,
	.cm-s-eclipse .CodeMirror-line>span>span::-moz-selection,
	.cm-s-eclipse .CodeMirror.cm-s-eclipse .CodeMirror-line>span>span::selection {
		background: rgba(73,72,62,.99);
	}
}
```

`.CodeMirror-gutter-wrapper` 是行号，与选中部分是无关的；
之后的代码，应当是由于没有选中超过两层的 `<span>` 而导致问题，但前前后后也没有 `#fff`；
浏览器的默认选中内容背景样式是蓝色的。

但，这里，选中后的三层嵌套 <span> 就是纯白色的…未能通过测试找到这是哪里来的 `#fff`。

而且，在手动设置主题的 CodeMirror 编辑器，比如 https://codemirror.net/demo/theme.html 中，这个问题根本不存在。在暴力猴以外的 CodeMirror 编辑器中测试时，选中后的三层嵌套 <span> 可能继承了父元素的样式，或者因为其他原因，并没有造成额外的麻烦。

换句话说，即使能修好，也不知道这个问题是哪里来的……

未测试亮色主题下的表现，可能也有一样的问题。

除了应用上面第一段 CSS 代码，也可以尝试直接加一个功能，**支持手动设置 CodeMirror 编辑器主题**，看看问题会不会自己消失。

在我看来，CodeMirror 的这个 CSS 选择器至少是写得不够好的，但这也可能有它特殊的考虑，由于不确定这个问题到底是哪里来的，我现在更加不确定要不要向 CodeMirror 提 issue 或者 PR…只好先在这里提交，看看能不能确定问题。
