### ISSUE TITLE
Color themes?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#924]
Can I install and/or switch to another color theme in VM?

**Comment by tophf** [comment]
Yes, use CSS in `settings` -> `advanced` -> `custom style`.

**Comment by soviet-man** [comment]
How can I know CSS classes of different editor tokens?

**Comment by tophf** [comment]
Use devtools to inspect the page.
See tutorials for `Stylish` or `Stylus` extension.

**Comment by tophf** [comment]
For CodeMirror themes you can copypaste them from https://github.com/codemirror/CodeMirror/tree/master/theme
Replace the theme name in the code with `cm-s-eclipse` so it looks like this:
```css
.cm-s-eclipse.CodeMirror { background: #f7f7f7; color: #3a3432; }
.cm-s-eclipse div.CodeMirror-selected { background: #d6d5d4; }

.cm-s-eclipse .CodeMirror-line::selection, .cm-s-eclipse .CodeMirror-line > span::selection, .cm-s-eclipse .CodeMirror-line > span > span::selection { background: #d6d5d4; }
.cm-s-eclipse .CodeMirror-line::-moz-selection, .cm-s-eclipse .CodeMirror-line > span::-moz-selection, .cm-s-eclipse .CodeMirror-line > span > span::selection { background: #d9d9d9; }

.cm-s-eclipse .CodeMirror-gutters { background: #f7f7f7; border-right: 0px; }
.cm-s-eclipse .CodeMirror-guttermarker { color: #db2d20; }
.cm-s-eclipse .CodeMirror-guttermarker-subtle { color: #807d7c; }
.cm-s-eclipse .CodeMirror-linenumber { color: #807d7c; }

.cm-s-eclipse .CodeMirror-cursor { border-left: 1px solid #5c5855; }

.cm-s-eclipse span.cm-comment { color: #cdab53; }
.cm-s-eclipse span.cm-atom { color: #a16a94; }
.cm-s-eclipse span.cm-number { color: #a16a94; }

.cm-s-eclipse span.cm-property, .cm-s-eclipse span.cm-attribute { color: #01a252; }
.cm-s-eclipse span.cm-keyword { color: #db2d20; }
.cm-s-eclipse span.cm-string { color: #fded02; }

.cm-s-eclipse span.cm-variable { color: #01a252; }
.cm-s-eclipse span.cm-variable-2 { color: #01a0e4; }
.cm-s-eclipse span.cm-def { color: #e8bbd0; }
.cm-s-eclipse span.cm-bracket { color: #3a3432; }
.cm-s-eclipse span.cm-tag { color: #db2d20; }
.cm-s-eclipse span.cm-link { color: #a16a94; }
.cm-s-eclipse span.cm-error { background: #db2d20; color: #5c5855; }

.cm-s-eclipse .CodeMirror-activeline-background { background: #e8f2ff; }
.cm-s-eclipse .CodeMirror-matchingbracket { text-decoration: underline; color: #a16a94 !important; }
```
